"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import mermaid from "mermaid";
import { useLanguage } from "@/components/language-provider";

export function BlogArticle({ html }: { html: string }) {
  const { t } = useLanguage();
  const articleRef = useRef<HTMLElement>(null);
  const renderedHtmlRef = useRef<string | null>(null);
  const mermaidIdRef = useRef(0);
  const [articleHtml, setArticleHtml] = useState(html);
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null);
  const [lightboxDiagram, setLightboxDiagram] = useState<string | null>(null);
  const [lightboxAlt, setLightboxAlt] = useState("");

  const closeLightbox = useCallback(() => {
    setLightboxSrc(null);
    setLightboxDiagram(null);
    setLightboxAlt("");
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeLightbox();
    };
    if (lightboxSrc || lightboxDiagram) {
      document.addEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "hidden";
    }
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "";
    };
  }, [lightboxSrc, lightboxDiagram, closeLightbox]);

  useEffect(() => {
    setArticleHtml(html);
    renderedHtmlRef.current = null;
    mermaidIdRef.current = 0;
  }, [html]);

  useEffect(() => {
    const article = articleRef.current;
    if (!article) return;

    const handleClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const diagram = target.closest(".mermaid-diagram");
      if (diagram) {
        e.preventDefault();
        setLightboxDiagram(diagram.innerHTML);
        setLightboxAlt("Mermaid diagram preview");
        return;
      }

      if (target.tagName !== "IMG") return;

      const img = target as HTMLImageElement;
      e.preventDefault();
      e.stopPropagation();

      if (img.closest("a")) {
        e.preventDefault();
      }

      setLightboxSrc(img.src);
      setLightboxAlt(img.alt || "");
    };

    article.addEventListener("click", handleClick);

    const images = article.querySelectorAll("img");
    images.forEach((img) => {
      (img as HTMLElement).style.cursor = "zoom-in";
    });

    return () => {
      article.removeEventListener("click", handleClick);
    };
  }, [html]);

  useEffect(() => {
    if (articleHtml !== html || renderedHtmlRef.current === html) return;

    // Wait for client-side providers to finish hydration before replacing DOM
    // generated by dangerouslySetInnerHTML. Otherwise React can replace the
    // original <pre> nodes while Mermaid is rendering them.
    const timer = window.setTimeout(() => {
      const article = articleRef.current;
      if (!article) return;
      renderedHtmlRef.current = html;

      void (async () => {
        const diagrams = Array.from(
          article.querySelectorAll<HTMLElement>('pre[data-language="mermaid"]')
        );
        if (!diagrams.length) return;

        mermaid.initialize({ startOnLoad: false, securityLevel: "strict" });

        for (const diagram of diagrams) {
          const definition = diagram.textContent?.trim();
          if (!definition) continue;

          try {
            const { svg } = await mermaid.render(
              `mermaid-${mermaidIdRef.current++}`,
              definition
            );
            const renderedDiagram = document.createElement("div");
            renderedDiagram.className = "mermaid-diagram";
            renderedDiagram.setAttribute("role", "button");
            renderedDiagram.setAttribute("tabindex", "0");
            renderedDiagram.setAttribute("aria-label", "Open Mermaid diagram preview");
            renderedDiagram.innerHTML = svg;
            diagram.replaceWith(renderedDiagram);
          } catch {
            // Keep the original code block visible when a Mermaid definition is invalid.
          }
        }

        // Persist Mermaid's generated SVG in React state so opening or closing
        // a lightbox cannot restore the original code blocks on re-render.
        setArticleHtml(article.innerHTML);
      })();
    }, 100);

    return () => window.clearTimeout(timer);
  }, [html, articleHtml]);

  return (
    <>
      <article
        ref={articleRef}
        className="prose dark:prose-invert"
        dangerouslySetInnerHTML={{ __html: articleHtml }}
      />

      {typeof document !== "undefined" && (lightboxSrc || lightboxDiagram) && createPortal(
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-3 sm:p-6"
          onClick={closeLightbox}
          role="dialog"
          aria-modal="true"
          aria-label={lightboxAlt || t.accessibility.imagePreview}
        >
          <div
            className={
              lightboxDiagram
                ? "relative h-[88vh] w-[94vw] max-w-[1400px]"
                : "relative flex flex-col items-end gap-2"
            }
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={closeLightbox}
              className={
                lightboxDiagram
                  ? "absolute right-3 top-3 z-10 rounded-full bg-black/65 p-2 text-white/90 shadow-lg transition-colors hover:bg-black/85 hover:text-white"
                  : "rounded-full bg-white/10 p-2 text-white/80 transition-colors hover:bg-white/20 hover:text-white"
              }
              aria-label={t.accessibility.close}
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>

            {lightboxSrc ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={lightboxSrc}
                alt={lightboxAlt}
                className="max-h-[80vh] max-w-[90vw] rounded-lg object-contain shadow-2xl"
              />
            ) : (
              <div
                className="mermaid-lightbox flex size-full items-center justify-center overflow-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-zinc-950 sm:p-10"
                dangerouslySetInnerHTML={{ __html: lightboxDiagram ?? "" }}
              />
            )}
          </div>
        </div>,
        document.body
      )}
    </>
  );
}
